### ISSUE TITLE
default function domain to .cluster.local

### ISSUE THREAD

**Issue by lkingland** [boson-project/faas#107]
We should probably implement the default domain as `.cluster.local` suffix for users initializing a Function without an explicitly provided name nor name derivable from directory structure, rather than generate an error or force the input.
For example
```
$ cd /home/alice/projects/test
$ faas create
OK test.cluster.local
```
(Currently this use case generates an error later in the process, on deploy)

For a little background: when creating a new Function, the primary use case is creating services with fully qualified domain names which are routable from localhost (i.e. ending in a TLD+1 public suffix)

For example, to create the following Functions:
```
www.example.com
my.example.com
cdn1.us-west2.example.co.uk
```
Is accomplished by either using the suggested project directory structure:
```
projects
├── example.co.uk
│   └── cdn1.us-west2
└── example.com
    ├── my
    └── www
```
or by explicitly providing the names
```
faas create www.example.com
faas create my.example.com
faas create cdn1.us-west2.example.co.uk
```
However, we do not yet support:
```
faas create test
OK test.cluster.local 
```

**Comment by zroubalik** [comment]
@lance this could be closed as well, if I am not mistaken? since #123 is merged in
