### ISSUE TITLE
Integration with Knative client as a plugin

### ISSUE THREAD

**Issue by lance** [boson-project/faas#119]
Documentation for this can be found here: https://github.com/knative/client/tree/master/docs/plugins

For each of the sub-tasks, there will be two things to accomplish.

* Implement the Plugin interface - https://github.com/knative/client/blob/fb47409837d0d201831840149565d82609bcab6b/pkg/kn/plugin/manager.go#L37-L53
* Register the plugin with kn - https://github.com/knative/client/tree/master/docs/plugins#plugin-inlining

Then one file, 'plugin_register.go' is added to our distribution of kn.

**Comment by zroubalik** [comment]
@dsimansk Is there anything else to be done, which is not covered by #155 and #163?
