### ISSUE TITLE
Proposal to decouple function name from function domain

### ISSUE THREAD

**Issue by lance** [boson-project/faas#123]
Currently, the CLI has been written to conflate the function name with the function domain. For example, creating a project in a directory, `foo`, produces the following:

```console
❯ ../faas init -l node                                                                                                         Wed 16 Sep 2020 09:49:18 AM EDT
Project path: /home/lanceball/src/go/src/github.com/boson-project/faas/foo
Project name: foo.faas.boson-project.github.com
Runtime: node
Trigger: http
```
Where the project name has been derived from the local directory. It is possible to provide a name to the `init` and create commands. For example,

```console
❯ faas init foo -l node                                                                                                541ms  Wed 16 Sep 2020 09:51:01 AM EDT
Project path: /home/lanceball/src/go/src/github.com/boson-project/faas/foo
Project name: foo
Runtime: node
Trigger: http
```
However, this produces problems during deployment.

```console
❯ faas build                                                                                                           545ms  Wed 16 Sep 2020 09:52:07 AM EDT
A repository for Function images is required. For example, 'docker.io/tigerteam'.

Repository for Function images: docker.io/lanceball
Building image: docker.io/lanceball/foo:latest

faas/foo on  main [$!?] is 📦 v0.1.0 via ⬢ v12.16.3 took 35s 
❯ faas deploy                                                                                                          35.8s  Wed 16 Sep 2020 09:52:48 AM EDT
Error: : Invalid value: "foo": should be a domain with at least two segments separated by dots
```

This is, of course, going to be confusing to the end user. "I just wanted to name my function something. Why is it failing?". 

In fact, if I manually edit `./.faas.yaml` to attempt to comply with the error message suggestion, I then get the following.

```console
❯ cat .faas.yaml                                                                                                        5.1s  Wed 16 Sep 2020 09:54:25 AM EDT
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .faas.yaml
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ name: foo.bar
   2   │ namespace: ""
   3   │ runtime: node
   4   │ image: docker.io/lanceball/foo:latest
   5   │ trigger: http
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

faas/foo on  main [$!?] is 📦 v0.1.0 via ⬢ v12.16.3 
❯ faas deploy                                                                                                          147ms  Wed 16 Sep 2020 09:54:30 AM EDT
Error: invalid service name 'foo.bar', must be at least three parts.
```

Not only is it unintuitive to conflate domain and name, it can cause real usability issues, and complicates our code base. It also ignores the fact that a function may move from domain to domain as it goes through a development/test/stage/prod pipeline. Additionally, domain management is really the baliwick of cluster configuration, and in the vast majority of cases, these two personas (developer / cluster admin) are going to be different people. 

While it is true that a function's name ultimately does become a part of the route, this should not be a concern of the function developer. For example, using the `kn` CLI, it's easy to create a function named `foo`. The route to the function ultimately does contain that name, but as a developer, I don't really care as long as the route is available.

```console
❯ kn service create foo --image docker.io/lanceball/foo:latest                                                         152ms  Wed 16 Sep 2020 10:00:20 AM EDT
Creating service 'foo' in namespace 'faas':

  0.037s The Configuration is still working to reflect the latest desired specification.
  0.286s The Route is still working to reflect the latest desired specification.
  0.587s Configuration "foo" is waiting for a Revision to become ready.
 12.846s ...
 12.883s Ingress has not yet been reconciled.
 12.937s unsuccessfully observed a new generation
 13.139s Ready to serve.

Service 'foo' created to latest revision 'foo-jfcdt-1' is available at URL:
http://foo.faas.127.0.0.1.nip.io
```

I recommend a change to effect the following.

* Derive the function name from the directory path if not provided (exists already), but limit it to the directory name instead of the full path
* Allow user to provide a name for `init` and `create` commands (exists already)
* Since `kn` names cannot have a `.` in them, continue to munge the name so that we prevent the user from experiencing an error if they name the function `foo.bar` for example. In that case, we can munge it to `foo-bar` and `kn` will be happy.

See: https://github.com/boson-project/faas/issues/47
See: https://github.com/boson-project/faas/issues/107
See: https://github.com/boson-project/faas/issues/94
See: https://github.com/boson-project/faas/issues/95
See: https://github.com/boson-project/faas/issues/86
See: https://github.com/boson-project/faas/issues/85

Note all of these issues are directly related to naming and DNS of functions. If we simply assume that the cluster is configured correctly, and ensure that any name provided or derived does not have a `.` in it, all of these issues essentially go away.

@boson-project/core we discussed this earlier in the week, please feel free to include your thoughts here.

**Comment by lance** [comment]
Currently, our flow is 

```
mkdir foo
cd foo
faas init -l node
```
Or in your example, @zroubalik it would be

```console
mkdir foo
faas init -p foo -l node
cd foo
```

I agree with your suggestion, Zbynek that the name should be required and not derived, with the following use cases. (Note: that a side effect of this approach is that the `-p` flag goes away for `init` and `create`, and there's a good argument to be made that it should go away altogether).

```console
faas init relative/path/to/foo -l node
cd relative/path/to/foo
cat .faas.yaml
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .faas.yaml
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ name: foo
   2   │ namespace: ""
   3   │ runtime: node
   4   │ image: docker.io/lanceball/foo:latest
   5   │ trigger: http
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
```console
faas init /absolute/path/to/foo -l node
cd /absolute/path/to/foo
cat .faas.yaml
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .faas.yaml
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ name: foo
   2   │ namespace: ""
   3   │ runtime: node
   4   │ image: docker.io/lanceball/foo:latest
   5   │ trigger: http
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
```console
mkdir relative/path/to/foo
faas init relative/path/to/foo -l node
cd relative/path/to/foo
cat .faas.yaml
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .faas.yaml
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ name: foo
   2   │ namespace: ""
   3   │ runtime: node
   4   │ image: docker.io/lanceball/foo:latest
   5   │ trigger: http
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
Note in the last case, the directory already exists but does not contain any contentious files.

**Comment by lance** [comment]
One use case I did not show is specifying the current directory. I think this should probably work as well.

```console
cd foo
faas init . -l node
cat .faas.yaml
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .faas.yaml
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ name: foo
   2   │ namespace: ""
   3   │ runtime: node
   4   │ image: docker.io/lanceball/foo:latest
   5   │ trigger: http
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by zroubalik** [comment]
> Currently, our flow is
> 
> ```
> mkdir foo
> cd foo
> faas init -l node
> ```
> 
> Or in your example, @zroubalik it would be
> 
> ```
> mkdir foo
> faas init -p foo -l node
> cd foo
> ```

Yeah, that's what I mean, there's a typo in the example, sorry for the confusion 🙄

I like the solution/usecases that you have presented here.

**Comment by matejvasek** [comment]
>mkdir foo
faas init -p foo -l node
cd foo

`Maven` or `Leiningen` project creation works that way too.

**Comment by matejvasek** [comment]
I mean they create new dir.

**Comment by nainaz** [comment]
I think it is important for the Function Author to not worry about domain name. They should just provide the function name and that is it. 

I also like the suggestion of not creating the dir first , but let the command create it. 
Q : How would this work for create. same as init? 
Q: what if user doesn't provide a dir name? rather than prompting, should we create a default one ?

**Comment by matejvasek** [comment]
For domain name we could introduce new sub-command like `faas expose fn-name url` command.

**Comment by lance** [comment]
>  Q : How would this work for create. same as init?

Yes, that's how I see it.

>  Q: what if user doesn't provide a dir name? rather than prompting, should we create a default one ?

I think the directory should be a required argument, but could be `.`. For example...

```console
cd my-fn-app
kn faas create -l node
# Error a directory name is required
kn faas create . -l node
cat .faas.yaml
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .faas.yaml
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ name: my-fn-app
   2   │ namespace: ""
   3   │ runtime: node
   4   │ image: docker.io/lanceball/foo:latest
   5   │ trigger: http
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by nainaz** [comment]
it seems weird that rather than saying function name is required we are saying directory name is required. Could we ask for function name and make a directory with that name then?

**Comment by zroubalik** [comment]
@nainaz yeah, that's exactly the way we want to go. User specifies a function name, a new directory with function stub inside will be create.

But there will be a possibility to create a function in the existing directory as well (in this case the name of the directory will be used as a name for the function).
