### ISSUE TITLE
Use unique name for built images

### ISSUE THREAD

**Issue by zroubalik** [boson-project/faas#140]
`faas build` currently produces image named eg `docker.io/zroubalik/myfunction:latest`.

We should add some hash to the name, to make the image unique.

Usecase: 
Let’s say, I’d like to create 2 different functions, but both named myfunction (deployed into different namespaces). Current soluiton will result in conflict

**Comment by rhuss** [comment]
The question is also whether could detect that conflict or whether it would just overwrite the other image. Using a random prefix doesn't help much either as this does not guarantee that there is no conflict (if you can't detect the conflict).

Just checking if the image exists in the registry might also not be good enough, as this could have been created just by a previous build from the current function.

**Comment by rhuss** [comment]
I wonder how other container-based faas (e.g. openfaas or riff) deal with this situation. Maybe its worth to have a look at them, too.
