### ISSUE TITLE
faas build & deploy should use SHA

### ISSUE THREAD

**Issue by zroubalik** [boson-project/faas#141]
`faas build` should note at the end result the SHA e.g. in faas.yaml that then could be picked up by `faas deploy`

**Comment by rhuss** [comment]
Quick question: How is this related to #140 ? Does this already solve the issue that is described in #140 ?

**Comment by lance** [comment]
> Quick question: How is this related to #140 ? Does this already solve the issue that is described in #140 ?

Personally, I think it solves the issue well enough for dev preview. What do you think @zroubalik?

**Comment by lance** [comment]
Hmm- taking a quick look at the Buildpack client, it doesn't seem that they expose the sha after the image is built. https://github.com/buildpacks/pack/blob/main/build.go#L175

I suppose after the build completes, we could query the docker daemon to get the image info and extract it from that. Hrm...

**Comment by rhuss** [comment]
Yes, this getting the SHA typically involves an additional query (could be the docker daemon where the image has been build or also the registry where the image is stored). You would ask for information about the image with the specific tag.

**Comment by rhuss** [comment]
Interestingly the build command also fetches the sha/id just for logging purpose: https://github.com/buildpacks/pack/blob/68dec3e856738048ca848f2addb3858a150e4411/build.go#L310 Not sure whether it can be exposed more easily

**Comment by zroubalik** [comment]
I dealt with the exactly same problem yesterday, seems like docker query is the only viable option.

For Buildpacks, there's https://github.com/buildpacks/imgutil library for inspecting the image (but it is using docker internally) so I think we can use the docker directly.
