### ISSUE TITLE
Replace appsody init

### ISSUE THREAD

**Issue by lkingland** [boson-project/faas#18]
The `init` step currently utilizes the `appsody` binary and custom stacks to initialize new Service Functions.  This should be replaced by either built-in templates or a git-repo-based solution.  Architecture TBD.

**Comment by lance** [comment]
I think `git clone -q` into a temp directory, then `mv node-template <project-dir>` (or whatever) is pretty straightforward, _not_ using the `git` binary though.

Let's iterate/brainstorm on potential extensibility here too

**Comment by matejvasek** [comment]
What about packaging template as tar.gz or zip and then download in via plain http(s)?

**Comment by lance** [comment]
@matejvasek that works too. I think keeping it simple is important and that's even simpler :). If we go with the tar.gz route, we'd still want to have the templates under RCS of course. Maybe it could be as simple as keeping the templates in github and tagging/releasing them. The CLI could just download the `.tgz` release files.
