### ISSUE TITLE
Remove the create command

### ISSUE THREAD

**Issue by zroubalik** [boson-project/faas#180]
As discussed several times, we should remove `create` command and rename `init` to `create` then.

As a result `faas create` will have the same functionality as `faas init` has currently.

**Comment by lkingland** [comment]
Agreed.  Now that the constituent steps of `create` have been exposed as individual sub-commands, having `create` is confusing.

**Comment by lance** [comment]
Closing. Fixed in https://github.com/boson-project/faas/pull/209
