### ISSUE TITLE
Quarkus template still exports "greet"

### ISSUE THREAD

**Issue by lance** [boson-project/faas#182]
I'm not sure exactly what's going on here. The template itself exports `echo`, but when I run `faas init`, followed by `faas build` the classes directory contains an application.properties file that has the `greet` function as the export. Could this be an old buildpack is still being used?

```
❯ faas init -l quarkus -t events
Project path: /home/lanceball/demo/quarkus
Function name: quarkus
Runtime: quarkus
Trigger: events

~/demo/quarkus is 📦 1.0.0-SNAPSHOT via ☕ v11.0.8 
❯ faas build
Building image: 
A registry for Function images is required. For example, 'docker.io/tigerteam'.

Registry for Function images: lanceball

~/demo/quarkus is 📦 1.0.0-SNAPSHOT via ☕ v11.0.8 took 25s 
❯ rg greet
target/classes/application.properties
1:quarkus.funqy.export=greet
```

**Comment by matejvasek** [comment]
@lance that's odd, in `src` it's OK, but for some reason `target` is bundled in template and it should't be.

**Comment by matejvasek** [comment]
I guess something wrong went with `pkger`. It really should be called while make.

**Comment by matejvasek** [comment]
@lance looks like this was broken as part of 74511948cefc368d898ad05b911fded74d44b759
I don't know how that could happen.

Were you testing the templates within source tree? If so, you might unknowingly commit some changes via pkger.
Or maybe merge/rebase issue?

I hate versioning generated files.

**Comment by matejvasek** [comment]
This is why we need integration tests.
