### ISSUE TITLE
Custom port for image repository is not respected

### ISSUE THREAD

**Issue by matejvasek** [boson-project/faas#185]
If using repository like my-repo:5000/default/bar, the ":5000/default/bar" part is removed during deploy.

**Comment by matejvasek** [comment]
This appeared after adding sha to image.

**Comment by matejvasek** [comment]
@lance we need to fix this right?

**Comment by lance** [comment]
Yes I think we should fix it.

**Comment by matejvasek** [comment]
I'll try this: https://stackoverflow.com/questions/37861791/how-are-docker-image-names-parsed

**Comment by zroubalik** [comment]
Good catch 👍
