### ISSUE TITLE
[usability] The default runtime choose is weird and biased

### ISSUE THREAD

**Issue by slinkydeveloper** [boson-project/faas#191]
**Does the issue result in incorrect behavior?**
This issue is a personal opinion, feel free to ignore.

After installing for the first time the tool, i run `kn faas create`/`kn faas init` and it creates a golang project. This seems to me like a biased choice and, somehow, this behaviour sounds weird to me, because i typed this command with the expectation that it would fail with something like :

> You didn't specified a runtime between "go", "quarkus" and "node"

**Suggest an alternative**
My feeling is that, after the setup, without any env vars configured, the command should fail with the above described command

**Comment by nainaz** [comment]
I agree. we should prompt to choose the runtime and event type.

**Comment by lance** [comment]
@nainaz I just closed this by defaulting to Node.js HTTP. By saying that we should prompt, are you suggesting that there be no actual defaults?

**Comment by nainaz** [comment]
no it is fine. I like interactive CLI. probably just me. We will wait for more feedback.
