### ISSUE TITLE
Rename binary to `function`

### ISSUE THREAD

**Issue by lance** [boson-project/faas#201]
Based on conversation during test day, the consensus is that the binary and subsequent `kn` plugin should be renamed to `functions`. This has implications both in the name of the binary, but also in the CLI help strings as the `faas.yaml` filename.

**Comment by lkingland** [comment]
`function` or `functions`?

**Comment by zroubalik** [comment]
I suppose it should be `function`

**Comment by zroubalik** [comment]
We should probaly rename env variables, such as `$FAAS_CONFIRM`,`$FAAS_IMAGE`, `$FAAS_PATH` and`$FAAS_REGISTRY`.

And what about  `quay.io/boson/faas` ?

**Comment by zroubalik** [comment]
Then we should follow up with renaming this repo from `boson-project/faas` -> `/boson-project/function` and change the occurrences in code (package..) :trollface:

**Comment by lance** [comment]
Also, this should include rename of `faas.yaml` to `function.yaml`.
