### ISSUE TITLE
Add all flags of `kn service apply` to `func deploy`

### ISSUE THREAD

**Issue by rhuss** [boson-project/faas#222]
As `kn service` allows many more options when creating a service, it would make sense to support those for `func create`, too.
Ideally the options could be reused from the kn code-base, so making those reusable should be a task for the knative client to implement.

As a workaround `kn service update` could be used to tweak service parameters.

**Comment by zroubalik** [comment]
Probalby a duplicate of: https://github.com/boson-project/faas/issues/164

**Comment by rhuss** [comment]
True, so let's close this. But let's keep in head to reuse the kn-code if possible.
