### ISSUE TITLE
binary build should include `pkger`

### ISSUE THREAD

**Issue by kameshsampath** [boson-project/faas#230]
currently when we add new tempaltes, we need to do `pkger` from the templates directory for it to be used with `func`.  There are lot of changes to have that step missed, hence its better to have it as part of `Makefile`

CC: @lkingland

**Comment by lkingland** [comment]
I don't see any reason we could not include:
```
go get github.com/markbates/pkger/cmd/pkger
pkger
```
as part of the build process.  

I wonder:  in a perfect world, would it be a separate Make target, only triggered if Make detects changes to any files in the `./templates` directory...

**Comment by lance** [comment]
> I wonder: in a perfect world, would it be a separate Make target, only triggered if Make detects changes to any files in the `./templates` directory, and set as a dependent target on the Build targets...

I'd say that we should to that even in __this__ world! :smile:
