### ISSUE TITLE
Create automated releases as drafts, or add tooling to generate changelogs

### ISSUE THREAD

**Issue by lance** [boson-project/faas#41]
The GH workflow for our releases sets `draft: false`. I wonder if we should create a release as a draft, and then manually update the release notes with a changelog of some kind.

Alternatively, we could use tooling like [`git-chglog`](https://github.com/git-chglog/git-chglog) to generate a changelog for the release and include that in the release description during the workflow.

**Comment by lance** [comment]
If the latter (generating a changelog), I think it would be good if we consider standardizing on commit message styles. I prefer [`conventional-commits`](https://www.conventionalcommits.org/en/v1.0.0/).

**Comment by lkingland** [comment]
This seems like a good idea to me.
