### ISSUE TITLE
faas binary reports incorrect version number

### ISSUE THREAD

**Issue by lance** [boson-project/faas#46]
Running `faas --version` produced `v0.0.0-source`.

```
❯ curl -L -s -o - faas.gz https://github.com/boson-project/faas/releases/download/v0.4.0/faas.gz | gunzip >faas && chmod 755 faas
❯ ./faas --version 
v0.0.0-source
```

**Comment by lkingland** [comment]
Interesting.  the logs of that release show it properly passing in the metadata necessary to show correct version:
https://github.com/boson-project/faas/runs/887258241?check_suite_focus=true
additionally, when running the command directly that the release target did:
`go build -ldflags "-X main.date=20200728T103438Z -X main.vers=v0.4.0 -X main.hash=0f39bac" ./cmd/faas`
it results in a binary which correctly reports the verbose version number.

**Comment by lkingland** [comment]
More interesting still:  It's working for me.
I see the problem.  The `version` subcommand was updated, but the `--version` flag was not:
```
$ wget https://github.com/boson-project/faas/releases/download/v0.4.0/faas.gz
$ gunzip faas.gz && chmod +x faas
$ ./faas --version
v0.0.0-source
$ ./faas version
20200719T162249Z-v0.4.0-0f39bac
```
As an aside, the prepended dataestamp I think shold change place with the semver tag, don't you think?

**Comment by lance** [comment]
Definitely move the datestamp to either the end of the string, or between semver and hash.

**Comment by lance** [comment]
[This line](https://github.com/boson-project/faas/blob/develop/cmd/root.go#L22) causes the `--version` flag to get auto created, and it seems that when `verboseVersion()` is called, `SetMeta()` has not yet been called, so the variables that populate the version string have not been set.

**Comment by lance** [comment]
Fixed in https://github.com/boson-project/faas/pull/52
