### ISSUE TITLE
template file permissons not retained on Windows

### ISSUE THREAD

**Issue by lkingland** [boson-project/faas#57]
File permissions are not preserved when initializing new funcitons on Windows.
This is very possibly a bug or missing feature in the `pkger` dependency.  If this is indeed the case, we would ideally resove by submitting a PR.

_Originally posted by @matejvasek in https://github.com/boson-project/faas/pull/49#issuecomment-665653798_

**Comment by matejvasek** [comment]
I think this is simple that `Windows` file modes don't map to `Unix` file modes well.

From golang doc:
```
On Windows, the mode must be non-zero but otherwise only the 0200 bit (owner writable) of mode is used; it controls whether the file's read-only attribute is set or cleared. attribute. The other bits are currently unused. Use mode 0400 for a read-only file and 0600 for a readable+writable file.
```

**Comment by matejvasek** [comment]
https://golang.org/pkg/os/#FileMode

**Comment by lkingland** [comment]
Perhaps the problem here could be resolved by removing the need for the Function developer to use an executable file at all.  For instance, with the Go project, the _only_ thing in the local directory after creating a function is the code itself:  a `function.go` file with the function which conforms to a specific function signature, and a `function_test.go` file which allows tests to be run.  Could the Quarkus stack perhaps wrap up some more of the plumbing such that the executible is not required?

**Comment by lkingland** [comment]
I believe the ideal solution here is to refactor the Quarkus buildpack to use something like jbang such that the files which are written to the local directory contain _only .java files_, and in particular no `mvn` executable.  This issue is technically invalid, so unless anyone has objections, I am closing this as such.
