### ISSUE TITLE
Cluster namespace should be configurable

### ISSUE THREAD

**Issue by lance** [boson-project/faas#62]
When running `faas create <runtime> --namespace foo`, the `--namespace` flag is referring to the image registry namespace, but there seems to be no way to declare the cluster namespace to deploy the function to. It's always `faas`. I wonder if it wouldn't be better to have `faas create <runtime> --repository quay.io/lanceball --namespace my-cluster-namespace`, consolidating the `--registry` and `--namespace` options into one `--repository` option, and use the `--namespace` flag for the cluster namespace.

**Comment by lance** [comment]
Also, it's odd to me that `--namespace` is required, but the user is prompted for this value anyway - but I suppose that's a different issue altogether.

**Comment by drekar** [comment]
I completely agree with this; it is odd.  My only trepedation is that "namespace" is a very Kubernetes-specific concept.  I am not sure how to abstract this, however, so perhaps it simply has to leak through for now.

**Comment by lkingland** [comment]
I completely agree with this; it is odd. We can combine Registry and Namespace into --repository, and repourpose --namespace to be Kubernetes namespace. My only trepidation is that "namespace" is a very Kubernetes-specific concept. I am not sure how to abstract this, however, so perhaps it simply has to leak through for now.

**Comment by lance** [comment]
Fixed in https://github.com/boson-project/faas/commit/5b4d97a44359ebb96fa78d6a63ab3b9744e79094
