### ISSUE TITLE
`faas list` does not seem to work

### ISSUE THREAD

**Issue by lance** [boson-project/faas#73]
```
 pwd                                                                                                                          Mon 17 Aug 2020 03:04:34 PM EDT
/home/lanceball/src/go/src/github.com/boson-project/faas/foo

faas/foo on  lance/9-add-path-flag-everywhere [$!?] is 📦 v0.1.0 via ⬢ v14.8.0 
❯ ls -a                                                                                                                        Mon 17 Aug 2020 03:04:34 PM EDT
  .    ..    .faas.yaml    index.js    local.js    package.json    README.md    test

faas/foo on  lance/9-add-path-flag-everywhere [$!?] is 📦 v0.1.0 via ⬢ v14.8.0 
❯ cat .faas.yaml                                                                                                               Mon 17 Aug 2020 03:04:38 PM EDT
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .faas.yaml
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ name: foo.faas.boson-project.github.com
   2   │ runtime: node
   3   │ tag: quay.io/lanceball/foo-func
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

faas/foo on  lance/9-add-path-flag-everywhere [$!?] is 📦 v0.1.0 via ⬢ v14.8.0 
❯ kn service list                                                                                                      152ms  Mon 17 Aug 2020 03:04:42 PM EDT
NAME                                 URL                                                                  LATEST                                       AGE    CONDITIONS   READY   REASON
foo-faas-boson--project-github-com   http://foo-faas-boson--project-github-com.default.127.0.0.1.nip.io   foo-faas-boson--project-github-com-jbghp-1   7d1h   3 OK / 3     True    

faas/foo on  lance/9-add-path-flag-everywhere [$!?] is 📦 v0.1.0 via ⬢ v14.8.0 
❯ ../faas list -v                                                                                                      142ms  Mon 17 Aug 2020 03:04:51 PM EDT

faas/foo on  lance/9-add-path-flag-everywhere [$!?] is 📦 v0.1.0 via ⬢ v14.8.0 
```

**Comment by lance** [comment]
Update: it's listing only functions deployed to the `faas` namespace.

**Comment by lkingland** [comment]
Upon thinking about this a bit, I think the most forward-compatible option here would be to consider that the FaaS system, when configured to use a Kubernetes cluster as the underlying Platform, always delegates to the K8S client for making requests.  This client is configured using `~/.kube/config`, which includes the current namespace configuration.
So how about we, in all cases, use the currently configured namespace (as the docs recommend):
```
kubectl config set-context --current --namespace=faas
```
And confirm that our code does not interfere with this setting.

By keeping the namespacing as a layer "below" the faas system (in the same way we expect the currently active cluster to be abstracted, credentials, connection address, etc) we are not only preventing a leak through the Platform abstraction, we're also allowing for support of different platforms which don't have the namespace concept.

Alternately, if we really do want to expose the concept of namespace through the abtraction, we would just need to agree to be on the hook to create a sensible default implementation in situations where it does not exist, such as localhost, single-node bare cluters, other cluster implementations, etc.  Thoughts??

**Comment by lance** [comment]
> So how about, in all cases, we let the currently configured namespace be determined by that system (the docs currently recommend setting this during configuration)

Agree. I don't think this eliminates the need for a `--namespace` flag though. 

> Alternately, if we really do want to expose the concept of namespace through the abstraction, we would just need to agree to be on the hook to create a sensible default implementation in situations where namespace does not exist by default, such as localhost, other cluster types, etc. 

This should be taken under consideration, for sure. However, I think for an initial Dev Preview release, we can assume that localhost and Kube/OCP are the only two supported platforms. In this case, I'm not sure that there is much to really do other than be clear that `delete`, `deploy` `update` and `list` commands are only relevant in the context of remote Kube/OCP deployments.

**Comment by lkingland** [comment]
OK, so we'll default to using the kubectl-defined namespace (not override), but if supplied, use it.  Additionally, in platforms that do not utilize the setting, for now it is ignored.

It seems to me upon reflection that, regardless of underlying platform (be that Kubernetes, localhost, or some future platform made deployable via Grid), that the concept of a namespace will be useful if not necessary for anything beyond toy deployments.  Woe be unto those who add complexity at such an early stage, but this may be part of the Irreducible Complexity of function-as-a-service offering.  This is closely related to #76 of course, which I have had to dig into in order to pre-test the binary for the Grid integration, so I can either do this one, or we could perhaps mark this issue as a duplicate?

**Comment by lance** [comment]
Fixed in https://github.com/boson-project/faas/pull/78
