### ISSUE TITLE
Use --namespace and --tag consistently across commands

### ISSUE THREAD

**Issue by lance** [boson-project/faas#76]
In this project the `--namespace` command has been used to indicate the Kubernetes namespace or alternatively the image repository namespace. Additionally, in some commands (e.g. `faas deploy`) the user-supplied image tag is handled as with other CLIs such as [`docker`](https://docs.docker.com/engine/reference/commandline/tag/) and [`podman`](http://docs.podman.io/en/latest/markdown/podman-tag.1.html). That is, the entire string, including the hostname, namespace (if any - it is not required) and a possible version tag. 

This project should normalize these usages across all commands by always referring to a project's image as a single name (i.e. it's "__tag__", and the namespace as a Kubernetes `namespace`. Where the latter is nonsensical, for example in the `deploy` and `update` commands, the CLI help text should clearly indicate that the command is only used when managing a function project on a cluster.

**Comment by lkingland** [comment]
Well it may not be perfect, but it's at least consistent now!  Do you think this is good to close as completed now @lance?

**Comment by lance** [comment]
Yep - big improvement!
