### ISSUE TITLE
faas CLI interactive prompt shouldn't ask for information already provided in parameters

### ISSUE THREAD

**Issue by zroubalik** [boson-project/faas#89]
If I run this `faas create` command with details specifed in the parameters, I don't expect to get asked about the same information later in the prompt. I know there is `-y` parameter, but IMHO this shouldn't be needed for already specified details.

```bash
$ faas create test2.apps.zroubali.devcluster.openshift.com --runtime go --repository docker.io/zroubalik --trigger http  
                                                                                          
Path to project directory (/Users/zroubali/boson/test2):
Function project name (test2.apps.zroubali.devcluster.openshift.com):
Verbose logging (y/N): y
Runtime of source (go):
Function Trigger (http):
Repository for Function images (docker.io/zroubalik):
Override default deploy namespace (zroubalik):
```

**Comment by rhuss** [comment]
Also, for me the default suggested as the "deploy namespace" doesn't be to be taken over when just hitting return

**Comment by lance** [comment]
I would like to see the behavior change so that the user faces fewer prompts if any by default. Instead of `-y` to skip prompts, perhaps a `-i` for 'interactive' to generate prompts. The information is useful to see, however, so for example in @zroubalik's case the output might be something like this.

```console
$ faas create test2.apps.zroubali.devcluster.openshift.com --runtime go --repository docker.io/zroubalik --trigger http  
Project name: test2.apps.zroubali.devcluster.openshift.com
Project path: /Users/zroubali/boson/test2
Runtime: go / http
Image repository: docker.io/zroubalik
Namespace: zroubalik
.....
Function deployed to http://test2-apps-zroubali-devcluster.openshift.com
$
```
