### ISSUE TITLE
path flag

### ISSUE THREAD

**Issue by lkingland** [boson-project/faas#9]
While the client library does expect path to be explicitly passed, the CLI does not currently expose this as a flag, instead always defaulting to the current working directory.

All commands which use code on disk (defaulting to current-working directory) should accept a --path flag to allow affecting change on a directory other than the execution directory.
For example:
```
faas create go --path ~/src/example.com/admin
```
should be equivalent to
```
cd ~/src/example.com/admin && faas create go
```

**Comment by lance** [comment]
This flag has been added to `build`, `create`, `deploy` and `init` commands. It should also be added to `run` and `update` and `delete` commands.

**Comment by lkingland** [comment]
The path flag is indeed plumbed in to every command now.  See #79 for the gory details.
