### ISSUE TITLE
default namespace (optional) has incorrect value displayed in CLI

### ISSUE THREAD

**Issue by zroubalik** [boson-project/faas#91]
If I run some `faas` command, I get asked about overriding default namespace:

```bash
$ faas deploy                                                                                                                                                                                                      
Override default namespace (optional) (zroubalik):
```

The displayed value `(zroubalik)` is not correct, even though the project is deployed in the correct default namespace. 

The displayed namespace value is probably taken from a `FAAS_NAMESPACE` variable that I have specified before (from my understanding this Variable is referring to image repo namespace, not k8s namespace).

**Comment by lance** [comment]
@zroubalik I think this is not a bug and working as intended. The `FAAS_NAMESPACE` environment variable overrides the command line arguments. If you unset `FAAS_NAMESPACE` it should work as expected.
