### ISSUE TITLE
cannot create Go function

### ISSUE THREAD

**Issue by zroubalik** [boson-project/faas#93]
Creation of Go functions is probably broken, if I initialize a function from an empty project I can see this error:
```
expected a function taking either no parameters, one or more of (context.Context, event.Event) ordered; function has too many parameters (3)
```

Full log:
```
$ faas create test.apps.zroubali.devcluster.openshift.com --runtime go --repository docker.io/zroubalik --trigger http -y

3/4 Deploying Function to cluster
Error: failed to deploy the service: RevisionFailed: Revision "test-apps-zroubali-devcluster-openshift-com-yzbtp-1" failed with message: Container failed with: listening on http port 8080 for JSON-encoded CloudEvents
expected a function taking either no parameters, one or more of (context.Context, event.Event) ordered; function has too many parameters (3)
..
StdOut: Creating service 'test-apps-zroubali-devcluster-openshift-com' in namespace 'atest':

  0.407s The Route is still working to reflect the latest desired specification.
  0.507s Configuration "test-apps-zroubali-devcluster-openshift-com" is waiting for a Revision to become ready.
121.433s Revision "test-apps-zroubali-devcluster-openshift-com-yzbtp-1" failed with message: Container failed with: listening on http port 8080 for JSON-encoded CloudEvents
expected a function taking either no parameters, one or more of (context.Context, event.Event) ordered; function has too many parameters (3)
.
121.520s Configuration "test-apps-zroubali-devcluster-openshift-com" does not have any ready Revision.
```

**Comment by rhuss** [comment]
This happened to me, too, when using the `http` trigger. For the `events` trigger it worked.

**Comment by lkingland** [comment]
The `http` functionality in the Go buildpack simply hasn't been created yet. It's next on the list to do, and I believe that @matejvasek just submitted a PR adding support for the HTTP function signatures (the templates may still need to be updated).  In the short term, until those PRs are merged, you can use `trigger --events` and it should work; you just need to whip up a CloudEvent.

**Comment by lance** [comment]
Fixed in https://github.com/boson-project/faas/commit/bb575b04c0ee9fa05cf755cf23da21c8cedd18da and https://github.com/boson-project/faas/commit/8012e195c3b25a10d17f37311144a376cc53262c and released in v0.6.2. Closing.

**Comment by matejvasek** [comment]
@lance Note that this will work only if buildpacks are published too.

**Comment by lance** [comment]
@matejvasek good point - will look into publishing these.

**Comment by matejvasek** [comment]
Works now, @zroubalik  could you please verify that?
