### ISSUE TITLE
faas create/deploy could suggest the correct domain 

### ISSUE THREAD

**Issue by zroubalik** [boson-project/faas#94]
When creating/deploying a function, faas CLI could suggest the correct domain as user doesn't have to look up for the current value. Kubernetes clusters could be deployed accross various clouds, where the domain could be generated, long and ungly

**Comment by lkingland** [comment]
This would be a nice addition.   If I am understanding you correctly, we would implement a suggestion feature, where creating a function `test`:
```
$ faas create test
```
Would reach out to the cluster to query domains for which the cluster has been configured, prompting the user to choose one, with the default being `.cluster.local`, and it being one of the options.

This seems useful especially for, as you mention, deploying Functions to clusters which have been exposed as remarkably long and domain names... which seems to be quite often.

**Comment by zroubalik** [comment]
Closing this as we decoupled the domain from the Function name
